update notebooks with automatic download of hippocampus dataset
AdaptiveMotorControlLab/CEBRA-demos pull request #4
Opened 2023-07-07 09:44 UTC by gonlairo

PR to update notebooks with automatic download of rat dataset.

2023-07-25 09:24 UTC, stes requested changes
Let's add the notebooks again with only the small change at the beginning of the header

2023-09-06 09:05 UTC, MMathisLab commented on Demo_cohomology.ipynb
> +    "ls data/rat_hippocampus"
this seems hard-coded for unix; what about windows support? @gonlairo

2023-09-08 12:33 UTC, stes requested changes
some smaller comments

2023-09-08 12:33 UTC, stes commented on Demo_hippocampus_multisession.ipynb
>   "metadata": {
I think here we want to keep the original kernel name in the metadata?

2023-09-08 12:33 UTC, stes commented on Demo_primate_reaching.ipynb
this here seems like a pretty big change, intended?

2023-09-08 12:33 UTC, stes commented on Demo_primate_reaching_mse_loss.ipynb
this here seems like a pretty big change, intended?

2023-09-08 12:33 UTC, stes commented on Demo_synthetic_exp.ipynb
this here seems like a pretty big change, intended?

2023-09-08 12:33 UTC, stes commented on README.rst
>  ``import os; os.environ['CEBRA_DATADIR'] = "path/to/your/data"`` at the
Can we add the code snippet from @MMathisLab diff here (#3 ) to the README here as well? We can remove it again once all datasets support auto-download.

2023-09-12 21:36 UTC, MMathisLab approved these changes

2023-09-12 22:36 UTC, stes approved these changes

2023-09-12 22:36 UTC, merged